name: FlyUI
main: JazzyDevZ/Main
version: 0.0.2
api: [3.0.0, 4.0.0]
author: JazzyDevZ

commands:
  fly:
    description: "Sends a form to you that enables fly mode"
permissions:
  fly.permission:
    default: false
